app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('personnel/delete/{task}', 'PersonnelController@getDelete');
Route::get('personnel/supprimerPersonnel/{task}', 'PersonnelController@supprimerPersonnel');

Route::get('/', 'AppController@home');
Route::get('dashborad', 'DashboradController@index');
Route::group(['namespace'=>'Admin','prefix'=>'admin'],function(){
	
 Route::resource('admins','AdminController');
});
/**************************Bulletin de Paie*********************************************************/
Route::resource('bulletinPaie','BulletinPaieController');
/**************************primes*********************************************************/
Route::resource('primes','PrimeController');


/**************************Conges*********************************************************/
Route::resource('conges','CongesController');

Route::get('conges/updateCongee/{personnel_id}', 'CongesController@updateCongee');
Route::any('conges/{conge_id}/updateCongePersonnell', 'CongesController@updateCongePersonnell');

/********************************************************************************************/
/**************************personnel*********************************************************/
Route::resource('personnel','PersonnelController');

/********************************************************************************************/
/********************Cacule salaier***********************/
Route::get('salaire', 'PersonnelController@salaire');

Route::post('calculeSalaire',['uses'=>'PersonnelController@calculeSalaire', 'as' => 'clsalaire'] );

/*********************************************************/
Route::resource('typeDeContrat','TypeDeContratController');

// Authentication routes...

//Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
// Route::match(['get', 'post'], '/', 'AppController@home');
// Route::get('test', 'AppController@test');

//Route::post('auth/facebookLogin/{offline?}', 'Auth\AuthController@facebookLogin');
// Route::post('signup', 'AppController@signup');

/*Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);*/

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'authz'],
    'roles' => ['admin'],
    'permissions' => ['can_edit']
], function()
{
    Route::get('/', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
});
*/


/*
|--------------------------------------------------------------------------
|  Routes Journal de paie Coût Total
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieCoutTotal', 'JournalPaieCoutTotalController@index');
/*
|--------------------------------------------------------------------------
|  Routes Journal de paie IRPP
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieIrpp', 'JournalPaieIrppController@index');

/*
|--------------------------------------------------------------------------
|  Routes Cnss
|--------------------------------------------------------------------------
*/
Route::get('cnss', 'CnssController@index');

/*
 ------------------------------------------------------------------------------------
Ajax
 -------------------------------------------------------------------------------------
 */

Route::get('updateAvance',['as' => 'Avance', 'uses' => 'PersonnelController@updateAvance']);

app/Http/Controllers/PersonnelController.php
<?php

namespace App\Http\Controllers;

use App\Cnss;
use App\Conges;
use App\JournalPaieCoutTotal;
use App\JournalPaieIrpp;
use App\Personnels;
use App\Prime;
use App\TypeContrat;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;
use Illuminate\Support\Facades\Validator;
use PhpParser\Node\Expr\Cast\Array_;
use App\Http\Requests\CreatePersonnelRequest;
//coefficion retenus cnss
define("COEFFICIENT_RETENUE_CNSS", 0.0918);
//coefficion Calcule Retenue Charge Patronal
define("COEFFICIENT_CHARGE_PATRONAl", 0.1607);
define("COEFFICIENT_TFP", 0.2);
define("COEFFICIENT_FOPROLOS", 0.1);
define("COEFFICIENT_ACCIDENT_TRAVAIL", 0.005);
//Nombre du Mois
define("NOMBERDUMOIS", 12);
// Déduction fix de Salaire imposable 1
define("DEDUCTIONFIX", 0.1);

// Déduction sur nomber d'enfants
define("DEDUCTION_NB_ENFANTS_1", 90);
define("DEDUCTION_NB_ENFANTS_2", 165);
define("DEDUCTION_NB_ENFANTS_3", 225);
define("DEDUCTION_NB_ENFANTS_4", 270);
// Nomber de jour de Conges
define("COEFFICIENT_NB_CONGEE", 2);
define ("AVANCEARRAY", serialize (array ()));

class PersonnelController extends Controller
{    static $order_primes = 0;
     public $avanceAll=array();
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */


    public function index()
    {
        $personnels = Personnels::where('deleted_at', '0')->get();
        // ***************  get value of montant_prime in table pivote   personnels_primem declare ************************
       // dd (  $personnels->primes[0]->pivot->montant_prime);
        //(array('id','post', 'nom','prenom','cin','cf','nbEnfant','dateNaissance' ,'dateEntree','typeDeContrat_id','dateDeFinDuContrat','NumCnss'));
        // $typeCont= \App\TypeContrat::where('id', $personnels->typeDeContrat_id)->get()->pluck('typeDeContrat');
        // $typeCont=TypeContrat::where( $personnels->typeDeContrat_id,'=','id');
        //   dd($personnels);
        // dd($personnels->getAttributes());
        return view('personnel/index', compact('personnels'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        $typedecontrat = TypeContrat::lists('type_de_contrat', 'id')->toArray();

        return view('personnel/create', compact('typedecontrat'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(CreatePersonnelRequest $request)
    {      /****************************Image personnel **************************************************************/
        //uploade images personnel



        $image = Input::file('image');
        $validator = Validator::make([$image], ['image' => 'required']);


        if (  $image!=null && $image->isValid() ) {
            $dt = Carbon::parse(Carbon::now());
            $date = $dt->timestamp ;
            $destinationPath = 'img/uploads'; // upload path
            $titleImages = Input::get('nom').'_'. Input::get('prenom');
            $titleImages= preg_replace('/\s+/', '_', $titleImages);

            $extension = Input::file('image')->getClientOriginalExtension(); // getting image extension
            $fileName = $titleImages.'_'.$date.'.'.$extension; // renameing image
           $moveImages=Input::file('image')->move($destinationPath, $fileName); // uploading file to given path
        }else {
            $fileName="";
        }

        /*********************************************************************************************************/
        //
        // dd($request->all());->input('name');
        $date_de_fin_du_contrat_request = $request->input('date_de_fin_du_contrat');

        $date_de_fin_du_contrat_request = $date_de_fin_du_contrat_request == '' ? '01/01/9999': $request->input(
            'date_de_fin_du_contrat'
        );
        //dd(   $date_de_fin_du_contrat_request );
        //$date_de_fin_du_contrat_request=Carbon::createFromFormat('d/m/Y', $date_de_fin_du_contrat_request);;

      //  $date_de_fin_du_contrat_request=$date_de_fin_du_contrat_request->format('Y-m-d');




        // remplace le valuer date_fin_du_contrat par la valuer date_de_fin_du_contrat_request
       //$request->merge(array('date_de_fin_du_contrat' => $date_de_fin_du_contrat_request));

        $personnel= new Personnels(array(
            'post' => Input::get('post'),
            'nom' => Input::get('nom'),
            'cin' => Input::get('cin'),
            'non_banque' => Input::get('non_banque'),
            'cf'=>Input::get('cf'),
            'adresse_email' => Input::get('adresse_email'),
            'tele_personnel' => Input::get('tele_personnel'),
            'nationalites' => Input::get('nationalites'),
            'date_naissance' => Input::get('date_naissance'),
            'date_entree' => Input::get('date_entree'),
            'type_de_contrat_id' => Input::get('type_de_contrat_id'),
            'date_de_fin_du_contrat' => $date_de_fin_du_contrat_request ,
            'num_cnss' => Input::get('num_cnss'),
            'rib_banque' => Input::get('rib_banque'),
            'fumez_vous'=> $request->fumez_vous[0],
            'etat_sante'=> $request->etat_sante[0],
            'buvze_vous'=> $request->buvze_vous[0],
            'lieu_naissance' => Input::get('lieu_naissance'),
            'adresse_domicile' => Input::get('adresse_domicile'),
            'image' =>$fileName
        ));

        $personnel->save();

       // $personnel = Personnels::findOrFail( $personnel->id);
        //$personnel = Personnels::create($request->all());

        $journalPaie = new JournalPaieCoutTotal ();
        $journalIrpp = new JournalPaieIrpp ();
        $conge = new Conges();
        $cnss = new Cnss();



        /******************************************************CALCUL IRPP  **************************************/
        // CALCUL Salaier Brut
        $SB = $journalPaie->salaire_brut = $this->getSalaireBrut(($request->nb_jour), ($request->salaire_du_jour));

        // CALCUL Retenue CNSS
        $RCNSS = $journalPaie->retenu_cnss = $this->getRetenueCNSS($SB);
        $cnss->retenue_cnss = $RCNSS;
        $chargePatronal = $this->getChargePatronal($SB);
        $journalPaie->charage_patronal = $chargePatronal;
        $cnss->charge_patronale = $chargePatronal;
        // Cacule Accident de travail
        $accidentTravail = $this->getAccidentTravail($SB);
        $cnss->accident_de_travail = $accidentTravail;

        // Calcul Total cnss
        $totaCnss = $this->getTotalCNSS($RCNSS, $chargePatronal, $accidentTravail);
        $cnss->cout_total_mensuel = $totaCnss;
        $cnss->cout_total_trimestriel = ($totaCnss / 4);
        // Cacule Salaire imposable 1
        $SIMP1 = $this->getSIMP1($SB, $RCNSS);

        // CALCUL Abattement
        $Abattement = $this->getAbattement($SIMP1);
        $journalIrpp->abttement = $Abattement;

        // ******************Cacule Déduction************************
        $DEDUCTION = 0;
        $cf = $personnel->cf;
        $nbenfant = ($personnel->nb_enfant);

        $DEDUCTION = $this->getSituation($cf, $nbenfant);
        $journalIrpp->deduction = $DEDUCTION;
        //*************************************************************
        // CALCUL Salaire imposable 2
        $SIMP2 = $this->getSIMP2($SIMP1, $Abattement, $DEDUCTION);
        $SIMP2 = ceil($SIMP2);
        $journalIrpp->salaire_impossable_2 = $SIMP2;
        // CALCUL Totaux
        $toteaux = $this->getTotaux($SIMP2);

        //CALCUL IRPP
        $irpp = $toteaux;
        $journalPaie->retenue_irpp = $irpp;
        $journalIrpp->irrp_annuel = $irpp;
        $journalIrpp->irrp_mensuel = ($irpp / NOMBERDUMOIS);
        //Salaire Imposable
        $SIMPFinal = $SB - $RCNSS;
        $journalPaie->salaier_imposable = $SIMPFinal;
        $journalIrpp->salaire_impossable = ($SIMPFinal / NOMBERDUMOIS);
        $journalIrpp->salaire_impossable_annuel = $SIMPFinal;
        //Salaire Net
        $salaierNet = $journalPaie->salaier_net = ($SB - ($RCNSS + $irpp));
        //CALCUL TFP
        $tfp = $journalPaie->tfp = $this->getTfp($SB);
        //CALCUL foprolos
        $foprolos = $journalPaie->foprolos = $this->getFoprolos($SB);
        // Sauvegarde les donnes dans la table journal_paie_cout_totals
        $journalCoutTotals = $journalPaie->Personnels()->associate($personnel);
        $journalCoutTotals->save();

        // Sauvegarde les donnes dans la table journal_paie_irpps
        $journalIrpp = $journalIrpp->Personnels()->associate($personnel);
        $journalIrpp->save();

        // Sauvegarde les donnes dans la table cnss
        $cnssSave = $cnss->Personnels()->associate($personnel);
        $cnssSave->save();
        // Sauvegarde  les conges
        $congeSave = $conge->Personnels()->associate($personnel);

        $date_entree = $personnel->getOriginal('date_entree');
        $mDate = Carbon::parse($date_entree);
        $diff = $mDate->diffInMonths();

        $congeSave->nb_jour_conges = $diff * COEFFICIENT_NB_CONGEE;
        $congeSave->date_demande_conge = ($mDate);
        $congeSave->save();

        return redirect(route('personnel.index'));
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $personnels = Personnels::findOrFail($id);

        if (is_null($personnels)) {
            abort(404);
        }

        return view(
            'personnel.show',
            compact('personnels')
        );

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */

resources/views/personnel/create.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <!--header tab -->
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1 class="">Personnel</h1>
                </div>
                <div class="col-lg-2   ">
                    <div class="pull-right ">

                        <a href="{!! URL::to('personnel') !!} " class="btn btn-primary btn-primary-header  ">
                            Back
                        </a>
                    </div>
                </div>
            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- end header tab -->

        <!--container Tab -->
        <div class="row"><!-- /.row -->
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Création personnel
                    </div>
                    {!! Form::open(['url' => route('personnel.store'),'files'=> true])  !!}
                    @include('personnel.form_',['submitButtonText'=>'Ajouter ']);
                    {!! Form::close() !!}
                </div><!-- /div panel- panel-default-->
            </div><!--col-lg-12 -->
        </div><!-- row -->
        <!--end container tab -->
    </div><!-- container tab -->

    </div>  <!-- /#page-wrapper -->







@endsection

resources/views/personnel/delete.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper" style="min-height: 184px;">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">Supprimé le personnel: {{$personnel->nom}}  {{$personnel->prenom}}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-8 col-lg-push-2 text-center">
                <div class="panel panel-red">
                    <div class="panel-heading">
                       <h5>voulez-vous vraiment supprimer</h5>
                    </div>
                    <div class="panel-body">
                        <div class="row">
                            <div class="col-lg-12 ">
                                <div class="col-lg-6 ">
                        <a href="{!! URL::to('personnel/supprimerPersonnel/'.$personnel->id) !!}" type="button" class="btn btn-danger btn-lg">Oui</a>
                                    </div>
                                <div class="col-lg-6 ">
                        <a href="{!! URL::to('personnel') !!}" type="button" class="btn  btn-info btn-lg">Non</a>
                                </div>
                      </div>
                         </div>
                    </div>

                </div>
            </div>
            <!-- /.col-lg-4 -->
        </div>
        <!-- /.row -->

        <!-- /.row -->
    </div>
@stop

resources/views/personnel/edit.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <!--header tab -->
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1 class="">Personnel</h1>
                </div>
                <div class="col-lg-2   ">
                    <div class="pull-right ">

                        <a href="{!! URL::to('personnel') !!} " class="btn btn-primary btn-primary-header  ">
                            Back
                        </a>
                    </div>
                </div>
            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- end header tab -->

        <!--container Tab -->
        <div class="row"><!-- /.row -->
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Création personnel
                    </div>

                    {!! Form::model($personnel,['method'=>'PATCH','action'=>['PersonnelController@update',$personnel->id]]) !!}
                    @include('personnel.form_',['submitButtonText'=>'Update ']);
                    {!! Form::close() !!}
                </div><!-- /div panel- panel-default-->
            </div><!--col-lg-12 -->
        </div><!-- row -->
        <!--end container tab -->
    </div><!-- container tab -->

    </div>  <!-- /#page-wrapper -->







@endsection

resources/views/personnel/index.blade.php
@extends('layout')


@section('content')

            <!-- Modal -->
<div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog modal-sm">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Avance</h4>
            </div>

            {!! Form::open(['route' => 'Avance', 'method' => 'GET']) !!}
            <div class="modal-body">

                <input type="text" class="form-control" id="montant-avance" value= "0"  name="montant_avance">
                <input type="hidden" class="form-control" id="id-personnel" value="0" name="id_personnel">
                <input type="hidden" name="_token" value="{{ csrf_token() }}">
            </div>
            <div class="modal-footer">
                <button type="submit" class="btn btn-warning" id="ajout-avance">Ajouter</button>
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
            {!! Form::close() !!}
        </div>
    </div>
</div>
</div>

<div id="page-wrapper">
    <div class="row">

        <div class="col-lg-12 page-header">
            <div class="col-lg-10 ">
                <h1 class="">Table Personnel</h1>
                <div id="target">

                </div>
            </div>
            <div class="col-lg-2 ">
                <div class="pull-right ">

                    <a href="{!! URL::to('personnel/create') !!} " class="btn btn-primary btn-primary-header  ">
                        Ajouter
                    </a>
                </div>
            </div>
        </div> <!-- /.col-lg-12 -->
    </div><!-- div row -->
    <!-- /.row -->
    <div class="row">
        <div class="col-lg-12">
            <div class="panel panel-default">
                <div class="panel-heading">

                </div>
                <!-- /.panel-heading -->
                <div class="panel-body">
                    <div class="dataTable_wrapper">
                        <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                            <thead>
                            <tr>
                                <th>Poste</th>
                                <th>Nom & Prénom</th>
                                {{--<th>Finger ID</th>--}}
                                <th>CIN</th>
                                <th>CF</th>
                                {{--<th>Nbre D'enfant</th>--}}
                                <th>Date de Naissance</th>
                                <th>Date d'entrée</th>
                                <th> Contrat</th>
                                <th> N° CNSS</th>
                                <th> Nombre du jour</th>
                                <th> Salaire du jour</th>
                                <th></th>
                                <th> Avance</th>
                                <th> Primes</th>
                                {{--<th>Date Fin du Contrat</th>--}}
                               <th>Bulltetin de paies</th>
                                <th>Modifier</th>
                                <th>Suprimer</th>
                                <th></th>
                            </tr>
                            </thead>
                            <div class="row">
                                @foreach ($personnels as $personnel)



                                    <tr>

                                        <td> {{($personnel->post)}} </td>
                                        <td> {{($personnel->nom)}} {{($personnel->prenom)}}  </td>
                                        {{--<td> </td>--}}
                                        <td> {{($personnel->cin)}} </td>


                                        <td>  {{Config::get('constants')[$personnel->cf] }} </td>
                                        {{--<td> {{($personnel->nbEnfant)}} </td>--}}
                                        <td> {{(($personnel->date_naissance))}} </td>
                                        <td> {{($personnel->dateEntree)}} </td>

                                        <td> {{($personnel->maContrat->type_de_contrat)}} </td>

                                        {{--<td> {{($personnel->dateDeFinDuContrat)}} </td>--}}
                                        <td> {{($personnel->num_cnss)}} </td>
                                        <td> {{($personnel->nomber_jour)}} </td>
                                        <td> {{($personnel->salaire_jour)}} </td>
                                        <td>
                                            <div type="button" id="avance" class="btn btn-info test"  val="{{$personnel->id }}" >ajouter avance
                                            </div>
                                        </td>
                                        <td>@if (unserialize($personnel->avance))
                                                {{array_sum(unserialize($personnel->avance)).' DT'}}
                                                @else {{'0'.' DT'}}
                                            @endif</td>
                                        <td>

                                            @foreach ($personnel->primes as $primes)
                                            @if ($personnel->prime == $primes->pivot->prime_order)
                                            </br>
                                            - {{$primes->description}} :
                                            {{$primes->pivot->montant_prime}}


                                            @endif




                                            @endforeach</td>
                                        <td>  
                                            @if ( ($personnel->jpCoutTotals->salaire_brut) >0 )
                                            <a href="{!! URL::to('bulletinPaie/'.$personnel->id) !!}"><i class="fa fa-file fa-2x"></i></a>
                                            @else <i>salaire brut pas encore calculé</i>
                                            @endif
                                        </td>

                                        <td>
                                            <a href="{!! URL::to('personnel/'.$personnel->id.'/edit') !!}"><i
                                                            class="fa fa-pencil"> </i></a>
                                        </td>
                                        <td>
                                            <a href="{!! URL::to('personnel/delete/'.$personnel->id) !!}"
                                               class="btn btn-danger  btn-sm"><i class="fa fa-times-circle-o"> </i></a>
                                        </td>
                                        <td>

                                            <a href="{{route('personnel.show', ['name' => $personnel->id])}}"
                                               class="btn btn-warning  btn-sm"><i class="fa fa-building-o"> </i></a>


                                        </td>

                                    </tr>

                                @endforeach
                            </div>

                        </table>
                    </div>
                    <!-- /.table-responsive -->

                    <!-- /.panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-12 -->
        </div>


        <!-- /.row -->
    </div>
    <!-- /#page-wrapper -->


</div>


@endsection

resources/views/personnel/show.blade.php
@extends('layout')



@section('content')
    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12">
                <h1 class="page-header">{{$personnels->nom}} {{$personnels->prenom}}</h1>
            </div>
            <!-- /.col-lg-12 -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Information personnelle</h4>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table">
                                <thead>

                                <tr class="info">
                                    <td>Nom & prénom:</td>
                                    <td>{{$personnels->nom}} {{$personnels->prenom}} </td>

                                </tr>
                                <tr class="info">
                                    <td>CIN:</td>
                                    <td> {{$personnels->cin}} </td>

                                </tr>
                                <tr class="info">
                                    <td>Situation familiale:</td>
                                    <td> {{ Config::get('constants')[$personnels->cf]}} </td>

                                </tr>
                                <tr class="info">
                                    <td> Nombre d'enfants:</td>
                                    <td> {{$personnels->nb_enfant}} </td>

                                </tr>
                                <tr class="info">
                                    <td> Date de naissance:</td>
                                    <td> {{$personnels->date_naissance}} </td>

                                </tr>


                                </tbody>
                            </table>
                        </div>
                        <!-- /.table-responsive -->

                    </div>
                    <!-- .panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-6 -->
            <div class="col-lg-6">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        <h4>Information professionnelle</h4>
                    </div>
                    <!-- /.panel-heading -->
                    <div class="panel-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>

                                <tr class="success">
                                    <td>Post :</td>
                                    <td>{{$personnels->post}}  </td>

                                </tr>
                                <tr class="success">
                                    <td>Type du Contrat :</td>
                                    <td> {{$personnels->maContrat->type_de_contrat}} </td>

                                </tr>

                                <tr class="success">
                                    <td> Date d'entrée :</td>
                                    <td> {{$personnels->date_entree}} </td>

                                </tr>
                                <tr class="success">
                                    <td> Date de fin du contrat:</td>
                                    <td> {{$personnels->date_de_fin_du_contrat}} </td>

                                </tr>
                                <tr class="success">
                                    <td> Numéro CNSS:</td>
                                    <td> {{$personnels->num_cnss}} </td>

                                </tr>
                                <tr class="success">
                                    <td> Congée payé:</td>
                                    <td> {{$personnels->conges_paye}} </td>

                                </tr>
                                <tr class="success">
                                    <td> Salaire brut</td>
                                    <td> {{$personnels->nb_jour * $personnels->salaire_du_jour}} </td>

                                </tr>


                                </tbody>
                            </table>
                        </div>
                    </div>
                    <!-- .panel-body -->
                </div>
                <!-- /.panel -->
            </div>
            <!-- /.col-lg-6 -->
        </div>
        <!-- /.row -->

    </div>




    </div>
    </div>
@stop