app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('personnel/delete/{task}', 'PersonnelController@getDelete');
Route::get('personnel/supprimerPersonnel/{task}', 'PersonnelController@supprimerPersonnel');

Route::get('/', 'AppController@home');
Route::get('dashborad', 'DashboradController@index');
Route::group(['namespace'=>'Admin','prefix'=>'admin'],function(){
	
 Route::resource('admins','AdminController');
});
/**************************Bulletin de Paie*********************************************************/
Route::resource('bulletinPaie','BulletinPaieController');
/**************************primes*********************************************************/
Route::resource('primes','PrimeController');


/**************************Conges*********************************************************/
Route::resource('conges','CongesController');

Route::get('conges/updateCongee/{personnel_id}', 'CongesController@updateCongee');
Route::any('conges/{conge_id}/updateCongePersonnell', 'CongesController@updateCongePersonnell');

/********************************************************************************************/
/**************************personnel*********************************************************/
Route::resource('personnel','PersonnelController');

/********************************************************************************************/
/********************Cacule salaier***********************/
Route::get('salaire', 'PersonnelController@salaire');

Route::post('calculeSalaire',['uses'=>'PersonnelController@calculeSalaire', 'as' => 'clsalaire'] );

/*********************************************************/
Route::resource('typeDeContrat','TypeDeContratController');

// Authentication routes...

//Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
// Route::match(['get', 'post'], '/', 'AppController@home');
// Route::get('test', 'AppController@test');

//Route::post('auth/facebookLogin/{offline?}', 'Auth\AuthController@facebookLogin');
// Route::post('signup', 'AppController@signup');

/*Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);*/

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'authz'],
    'roles' => ['admin'],
    'permissions' => ['can_edit']
], function()
{
    Route::get('/', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
});
*/


/*
|--------------------------------------------------------------------------
|  Routes Journal de paie Coût Total
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieCoutTotal', 'JournalPaieCoutTotalController@index');
/*
|--------------------------------------------------------------------------
|  Routes Journal de paie IRPP
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieIrpp', 'JournalPaieIrppController@index');

/*
|--------------------------------------------------------------------------
|  Routes Cnss
|--------------------------------------------------------------------------
*/
Route::get('cnss', 'CnssController@index');

/*
 ------------------------------------------------------------------------------------
Ajax
 -------------------------------------------------------------------------------------
 */

Route::get('updateAvance',['as' => 'Avance', 'uses' => 'PersonnelController@updateAvance']);

app/Conges.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Conges extends Model
{

    //
    protected $fillable = [
        'nb_jour_conges',
        'date_demande_congee',

    ];
    public function Personnels()
    {
        return $this->belongsTo('App\Personnels');
    }
}

app/Http/Controllers/CongesController.php
<?php

namespace App\Http\Controllers;

use App\Conges;
use App\ListesDemandsConges;
use App\Personnels;
use Carbon\Carbon;
use Illuminate\Http\Request;

use App\Http\Requests;
use Illuminate\Support\Facades\Input;

// Nomber de jour de Conges
define("COEFFICIENT_NB_CONGEE_", 2);

class CongesController extends Controller
{
    /**
     * Display a listing of the resource.
     *           $date_entree=  $conge->getOriginal('date_entree') ;
     * $mDate = Carbon::parse($date_entree);
     * echo  $mDate->diffInMonths().'<br>';
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $conges = Personnels::where('deleted_at', '=', 0)->with('conges')->get();


        foreach ($conges as $conge) {

            $date_entree = $conge->getOriginal('date_entree');
            $mDate = Carbon::parse($date_entree);
            $diff = $mDate->diffInMonths();
            $nb_jour_conges = $diff * COEFFICIENT_NB_CONGEE_;
            $nb_jour_de_conge_reste = $nb_jour_conges - $conge->conges->somme_conge_demander;
            $updateConges = array(
                'nb_jour_conges' => $nb_jour_conges,
                'nb_jour_de_conge_reste' => $nb_jour_de_conge_reste,
            );
            Conges::where('personnels_id', $conge->id)
                ->update($updateConges);

        }
        $conges = Personnels::where('deleted_at', '=', 0)->with('conges')->get();

        return view('conge/index', compact('conges'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {

    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {


    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {

        if (!(ListesDemandsConges::get()->isEmpty())) {
            $Listconges = ListesDemandsConges::where('personnel_id', $id)
                ->orderBy('created_at', 'asc')
                ->get();


        } else {

            $Listconges = ListesDemandsConges::get();

        }

        return view('conge/show', compact('Listconges'));

    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

        $conge = Personnels::where('deleted_at', '=', 0)->with('conges')->findOrFail($id);

        return view('conge/create', compact('conge'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $conge = Personnels::where('deleted_at', '=', 0)->with('conges')->findOrFail($id);


        $nbjourTotal = ($conge->conges->nb_jour_conges);
        $nb_jouer_conge_demander = $request->nb_jouer_conge_demander;
        $date_de_debut_conge = $request->date_de_debut_conge;
        $date_de_fin_conge = $request->date_de_fin_conge;
        $description = $request->description;


        $listPersonnel = ListesDemandsConges::where('personnel_id', $conge->id)->get();

        if ($listPersonnel->isEmpty()) {
            // Si personnel not exite in tab listes_demandes_conges
            $nb_jour_de_conge_reste = $nbjourTotal - $nb_jouer_conge_demander;
            $somme_conge_demander = $nb_jouer_conge_demander;
            $nb_jour_de_conge_obtenu = $nb_jouer_conge_demander;

        } else {
            // Si un personnal a déja demander un conge
            foreach ($listPersonnel as $lis) {
                $somme_conge_demander = +$lis->somme_conge_demander;
            }
            $somme_conge_demander = $somme_conge_demander + $nb_jouer_conge_demander;
            $nb_jour_de_conge_reste = $nbjourTotal - $somme_conge_demander;
            $nb_jour_de_conge_obtenu = $somme_conge_demander;


        }
        $arrayList = [
            'nom' => $conge->nom,
            'prenom' => $conge->prenom,
            'personnel_id' => $conge->id,
            'date_de_debut_conge' => $date_de_debut_conge,
            'date_de_fin_conge' => $date_de_fin_conge,
            'nb_jouer_conge_demander' => $nb_jouer_conge_demander,
            'nb_jouer_conge_demander' => $nb_jouer_conge_demander,
            'somme_conge_demander' => $somme_conge_demander,
            'nb_jour_de_conge_obtenu' => $nb_jour_de_conge_obtenu,
            'nb_jour_de_conge_reste' => $nb_jour_de_conge_reste,
            'type_conge'=>$request->type_conge,
            'description' => $description,


        ];
        $updateConges = array(
            'somme_conge_demander' => $somme_conge_demander,
            'nb_jour_de_conge_obtenu' => $nb_jour_de_conge_obtenu,
            'nb_jour_de_conge_reste' => $nb_jour_de_conge_reste,
        );
        Conges::where('personnels_id', $conge->id)
            ->update($updateConges);
        $list = ListesDemandsConges::create($arrayList);

        return redirect(route('conges.index'));
    }

    public function updateCongee(Request $request, $id)
    {
        //  $conge = Personnels::where('deleted_at', '=', 0)->with('conges')->findOrFail($id);
        $conge = ListesDemandsConges::where('id', $id)->first();


        return view('conge/edit', compact('conge'));

    }

    public function updateCongePersonnell(Request $request,$id)
    {
        $congeList = ListesDemandsConges::where('id', $id)->first();
        $personnels = Personnels::where('deleted_at', '=', 0)->with('conges')->findOrFail($congeList->personnel_id);
        $AllNbJour=($personnels->conges->nb_jour_conges);
        $AllNbJourReste=($personnels->conges->nb_jour_de_conge_reste);
        $Allsomme_conge_demander=($personnels->conges->somme_conge_demander);

        $TempsNbCongeObtenu=($congeList->nb_jour_de_conge_obtenu);

        $currentNomberDeJourDemander=($congeList->nb_jouer_conge_demander);

        $TempsSommeJourCongee=$Allsomme_conge_demander+$AllNbJourReste;

        $new_nb_jour_de_conge_reste=$TempsSommeJourCongee-$request->nb_jouer_conge_demander;



        $newSommeCongee=$AllNbJour- $new_nb_jour_de_conge_reste;


       // convert to date carbon
        $date_de_debut_conge = $request->date_de_debut_conge;
        $date_de_debut_conge=Carbon::createFromFormat('d/m/Y', $date_de_debut_conge);;
        $date_de_debut_conge->format('Y-m-d');

        // convert to date carbon
        $date_de_fin_conge =$request->date_de_fin_conge;
        $date_de_fin_conge=Carbon::createFromFormat('d/m/Y', $date_de_fin_conge);;
        $date_de_fin_conge->format('Y-m-d');

        $updateListsConges = array(
            'date_de_debut_conge' => $date_de_debut_conge,
            'date_de_fin_conge' => $date_de_fin_conge,
            'nb_jouer_conge_demander' => $request->nb_jouer_conge_demander,
            'somme_conge_demander' => $newSommeCongee,
            'nb_jour_de_conge_obtenu' => $currentNomberDeJourDemander,
            'nb_jour_de_conge_reste' => $new_nb_jour_de_conge_reste,
            'description' =>$request->description,
        );
        ListesDemandsConges::where('id', $id)
            ->update($updateListsConges);
        $congeLists = ListesDemandsConges::where('personnel_id', $congeList->personnel_id)->get();
        $newSommeCongeeAll=0;
        foreach ($congeLists as $congelist) {
            $newSommeCongeeAll+=$congelist->nb_jouer_conge_demander;
        }

        $updateConges = array(
            'somme_conge_demander' => $newSommeCongeeAll,
            'nb_jour_de_conge_obtenu' => $newSommeCongee,
            'nb_jour_de_conge_reste' => $AllNbJour-$newSommeCongeeAll,
        );
        Conges::where('personnels_id', $congeList->personnel_id)
            ->update($updateConges);

        return redirect('conges/'. $congeList->personnel_id);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/conge/create.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <!--header tab -->
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1>Demande de Congés : {{$conge->nom}} {{ $conge->prenom }}</h1>
                </div>
                <div class="col-lg-2   ">
                    <div class="pull-right ">

                        <a href="{!! URL::to('conges') !!} " class="btn btn-primary btn-primary-header  ">
                            Back
                        </a>
                    </div>
                </div>
            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- end header tab -->

        <!--container Tab -->
        <div class="row"><!-- /.row -->
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Demande de Congés
                    </div>
                    {!! Form::open( array('action' => array('CongesController@update', $conge->id),'method' => 'put')) !!}

                    @include('conge.form_',['submitButtonText'=>'Ajouter '])
                    {!! Form::close() !!}
                </div><!-- /div panel- panel-default-->
            </div><!--col-lg-12 -->
        </div><!-- row -->
        <!--end container tab -->
    </div><!-- container tab -->

    </div>  <!-- /#page-wrapper -->







@endsection

resources/views/conge/edit.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <!--header tab -->
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1>Demande de Congés : {{$conge->nom}} {{ $conge->prenom }}</h1>
                </div>
                <div class="col-lg-2   ">
                    <div class="pull-right ">

                        <a href="{!! URL::to('conges/'.$conge->personnel_id) !!} " class="btn btn-primary btn-primary-header  ">
                            Back
                        </a>
                    </div>
                </div>
            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- end header tab -->

        <!--container Tab -->
        <div class="row"><!-- /.row -->
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Demande de Congés
                    </div>



                    {!! Form::model($conge,['method'=>'PATCH','action'=>['CongesController@updateCongePersonnell',$conge->id]]) !!}
                    @include('conge.form_',['submitButtonText'=>'Update '])
                    {!! Form::close() !!}
                </div><!-- /div panel- panel-default-->
            </div><!--col-lg-12 -->
        </div><!-- row -->
        <!--end container tab -->
    </div><!-- container tab -->

    </div>  <!-- /#page-wrapper -->







@endsection

resources/views/conge/form_.blade.php
<div class="panel-body">

    <div class="row">
        <!--  tab  content-->
        <div class="tab-content">
            <!-- General tab-->
            <div class="tab-pane active" id="tab-general">

                    <div class="col-lg-8 col-lg-offset-2">


                        <input type="hidden" name="_token" value="{{csrf_token()}}">

                    <div class="form-group  {{ $errors->has('nb_jour_conges') ? 'has-error' : '' }}">
                        {!! Form::label('Nomber des jours du conges') !!}
                        <div class="controls">
                            {!! Form::text('nb_jouer_conge_demander', null, array('class' => 'form-control')) !!}
                            <span class="help-block">{{ $errors->first('nb_jour_conges', ':message') }}</span>
                        </div>
                    </div>

                        <div class="form-group  {{ $errors->has('date_de_debut_conge') ? 'has-error' : '' }}" id="groupDebutConge">
                            {!! Form::label('Date debut conges') !!}
                            <div class="controls">
                                {!! Form::text('date_de_debut_conge', null, array('class' => 'form-control','id'=>'dateDebutConge')) !!}
                                <span class="help-block">{{ $errors->first('date_de_debut_conge', ':message') }}</span>
                            </div>
                        </div>
                        <div class="form-group  {{ $errors->has('date_de_fin_conge') ? 'has-error' : '' }}" id="groupFindConge">
                            {!! Form::label('Date fin conges') !!}
                            <div class="controls">
                                {!! Form::text('date_de_fin_conge', null, array('class' => 'form-control','id'=>'dateFinConge')) !!}
                                <span class="help-block">{{ $errors->first('date_de_fin_conge', ':message') }}</span>
                            </div>
                        </div>
                        <div class="form-group">
                            {!! Form::label('Type de congé?: ') !!}
                            <div class="row">
                                               <br>
                                <div class="col-lg-12">
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'maladie_obligation',  isset($conge)?$conge->type_conge=='maladie_obligation' : null, ['class' => 'filecheck']) !!}
                                            Maladie Obligation
                                           </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge','conge',isset($conge) ?$conge->type_conge=='conge' : null, ['class' => 'filecheck']) !!}
                                            Congé
                                        </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'deces', isset($conge)?$conge->type_conge=='deces' : null, ['class' => 'filecheck']) !!}Décés

                                        </label>
                                        </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'conge_sans_solde', isset($conge)?$conge->type_conge=='conge_sans_solde' : null, ['class' => 'filecheck']) !!}Congé sans solde

                                        </label>
                                        </div>
                                    </div>
                                        <br><br>
                                <div class="col-md-12">
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'militaires', isset($conge)?$conge->type_conge=='militaires' : null, ['class' => 'filecheck']) !!}militaires

                                        </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'activites_judiciaires', isset($conge)?$conge->type_conge=='activites_judiciaires' : null, ['class' => 'filecheck']) !!}Activités
                                            judiciaires

                                        </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong ">
                                            {!! Form::checkbox('type_conge', 'conge_parental', isset($conge)?$conge->type_conge=='conge_parental' : null, ['class' => 'filecheck']) !!}
                                            Congé parental

                                        </label>
                                    </div>
                                    <div class="col-lg-3">
                                        <label class="checkbox-inline filecheckcong">
                                            {!! Form::checkbox('type_conge', 'autre', isset($conge)?$conge->type_conge=='autre' : null, ['class' => 'filecheck']) !!}
                                           Autre

                                        </label>
                                    </div>
                            </div>
                        </div>
                        <div class="form-group  {{ $errors->has('conge_description') ? 'has-error' : '' }}" id="groupConge_descritption">
                            {!! Form::label('Description') !!}
                            <div class="controls">
                                {!! Form::textarea('description', null, array('class' => 'form-control','id'=>'conge_description','rows'=>"3")) !!}
                                <span class="help-block">{{ $errors->first('conge_description', ':message') }}</span>
                            </div>
                        </div>

                    </div>  <!-- /.col-lg-6-->
            </div>     <!-- tab pane -->
        </div> <!--tab content -->

        <div class="col-lg-12">
            <div class="col-lg-3 col-lg-push-3">
                <button type="reset" class="btn btn-danger btn-block">Anuuler</button>
                </button>
            </div>
            <div class="col-lg-3  col-lg-push-3">
                            {!! Form::submit($submitButtonText,['class'=>
                            'btn btn btn-success btn-block']) !!}



            </div>
        </div>

    </div><!-- /div row -->

</div><!-- /panel-body -->

resources/views/conge/index.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1 class=""> Gestion des congés</h1>
                </div>

            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                        Liste du personnl
                    </div>
                    <!-- /.panel-heading -->

                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>Post</th>
                                    <th>Nom & Prénom</th>
                                    <th>Congé payé consommé  </th>
                                    <th>Congé payé restants</th>
                                    <th>Jour de entree</th>
                                    <th> </th>
                                    <th> </th>
                                    <th> </th>
                                </tr>
                                </thead><div class="row">
                                    @foreach ($conges as $ct)
                                        <tr>
                                            <td>{{$ct->post}}   </td>
                                            <td> {{$ct->prenom}} {{$ct->nom}} </td>
                                            <td> {{$ct->conges->somme_conge_demander}} <small>Jours</small></td>
                                            <td> {{$ct->conges->nb_jour_de_conge_reste}} <small>Jours</small></td>
                                            <td> {{$ct->date_entree}} </td>
                                            <td><a href="{!! URL::to('conges/'.$ct->id.'/edit/' ) !!}" type="button" class="btn btn-primary btn-sm center">Demande conges</a></td>
                                            <td>
                                                <a  href="{!! URL::to('conges/') !!}" class="btn btn-link btn-sm"><i class="fa fa fa-pencil"> </i></a>
                                            </td>
                                            <td>
                                                <a href="{{route('conges.show', ['id' => $ct->id])}}" class="btn btn-warning  btn-sm"><i class="fa fa-building-o"> </i></a>
                                            </td>
                                        </tr>
                                    @endforeach
                                </div>

                            </table>
                        </div>
                        <!-- /.table-responsive -->

                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>


            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->




@endsection

resources/views/conge/show.blade.php
@extends('layout')



@section('content')
    <div id="page-wrapper">

        @if(!($Listconges->isEmpty()))
        <div class="row">

            <div class="col-lg-12">
                <h1 class="page-header">{{$Listconges->get(0)->nom}} {{$Listconges->get(0)->prenom}}</h1>

            </div>
            <!-- /.col-lg-12

             -->
        </div>
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-8 col-lg-push-2">
                <div class="panel panel-default">
                    <div class="panel-heading heading-conges-lists">

                        <div class="row">
                            <div class="col-lg-6 col-xs-6"> Détails Congés</div>
                            <div class="col-lg-6 col-xs-6">
                                <div class="col-lg-8 col-lg-push-4 col-md-8 col-md-push-6   col-sm-6 col-sm-push-6 col-xs-6 col-xs-push-6">
                                    <div class="pull-left">Congés restants: {{$Listconges->last()->nb_jour_de_conge_reste}} <small>Jours</small></div>
                                </div>
                            </div>
                        </div>

                    </div>


                    <!-- /.panel-heading -->
                    <div class="panel-body">

                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>

                                    <th>Debut conge</th>
                                    <th>Fin conge</th>
                                    <th>Conge demander</th>
                                    <th>Description </th>
                                    <th>Modifier </th>
                                </tr>
                                </thead>
                                <tbody>
                                @foreach ($Listconges as $key => $ls)
                                <tr class="{{$key%2==0?'danger':'warning'}}">
                                    <td>{{$ls->date_de_debut_conge}}</td>
                                    <td>{{$ls->date_de_fin_conge}}</td>
                                    <td>{{$ls->nb_jouer_conge_demander}} <small>Jours</small></td>
                                    <td>{{ ($ls->description)}}</td>
                                    <td>   <a  href="{!! URL::to('conges/updateCongee/'.$ls->id) !!}" class="btn btn-link btn-sm"><i class="fa fa fa-pencil"> </i></a></td>
                                </tr>
                                @endforeach
                                </tbody>
                            </table>

                        </div>
                        <!-- /.table-responsive -->
                    </div>
                    <!-- /.panel-body -->


                </div>
                <!-- /.panel -->
            </div>

        </div>

        @else
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-6 col-lg-push-3">
                    <h1 class="page-header">Aucune congé demande</h1>
                </div>
                <!-- /.col-lg-12 -->
            </div>
            <!-- /.row -->
        </div>
        <!-- /.row -->
        @endif
    </div>





@stop