app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('personnel/delete/{task}', 'PersonnelController@getDelete');
Route::get('personnel/supprimerPersonnel/{task}', 'PersonnelController@supprimerPersonnel');

Route::get('/', 'AppController@home');
Route::get('dashborad', 'DashboradController@index');
Route::group(['namespace'=>'Admin','prefix'=>'admin'],function(){
	
 Route::resource('admins','AdminController');
});
/**************************Bulletin de Paie*********************************************************/
Route::resource('bulletinPaie','BulletinPaieController');
/**************************primes*********************************************************/
Route::resource('primes','PrimeController');


/**************************Conges*********************************************************/
Route::resource('conges','CongesController');

Route::get('conges/updateCongee/{personnel_id}', 'CongesController@updateCongee');
Route::any('conges/{conge_id}/updateCongePersonnell', 'CongesController@updateCongePersonnell');

/********************************************************************************************/
/**************************personnel*********************************************************/
Route::resource('personnel','PersonnelController');

/********************************************************************************************/
/********************Cacule salaier***********************/
Route::get('salaire', 'PersonnelController@salaire');

Route::post('calculeSalaire',['uses'=>'PersonnelController@calculeSalaire', 'as' => 'clsalaire'] );

/*********************************************************/
Route::resource('typeDeContrat','TypeDeContratController');

// Authentication routes...

//Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
// Route::match(['get', 'post'], '/', 'AppController@home');
// Route::get('test', 'AppController@test');

//Route::post('auth/facebookLogin/{offline?}', 'Auth\AuthController@facebookLogin');
// Route::post('signup', 'AppController@signup');

/*Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);*/

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'authz'],
    'roles' => ['admin'],
    'permissions' => ['can_edit']
], function()
{
    Route::get('/', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
});
*/


/*
|--------------------------------------------------------------------------
|  Routes Journal de paie Coût Total
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieCoutTotal', 'JournalPaieCoutTotalController@index');
/*
|--------------------------------------------------------------------------
|  Routes Journal de paie IRPP
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieIrpp', 'JournalPaieIrppController@index');

/*
|--------------------------------------------------------------------------
|  Routes Cnss
|--------------------------------------------------------------------------
*/
Route::get('cnss', 'CnssController@index');

/*
 ------------------------------------------------------------------------------------
Ajax
 -------------------------------------------------------------------------------------
 */

Route::get('updateAvance',['as' => 'Avance', 'uses' => 'PersonnelController@updateAvance']);

app/Prime.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Prime extends Model
{    protected $fillable = ['description'];//

    public function personnel()
    {
        return $this->belongsToMany('App\Personnels')->withTimestamps();
    }
}

app/Http/Controllers/PrimeController.php
<?php

namespace App\Http\Controllers;

use App\Personnels;
use App\Prime;
use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Input;
use Illuminate\Support\Facades\Session;

//Nombre du Mois
define("NOMBERDUMOIS", 12);

class PrimeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $primes = Prime::get();


        return view('prime/index', compact('primes'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('prime/create_edit');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $primes = Prime::create($request->all());

        return redirect(route('primes.index'));
        /*
         *
         *    $personel_id=( Input::get('personnel_id'));
          $salaire_du_jour=( Input::get('salaire_du_jour'));
           $nb_jour=( Input::get('nb_jour'));
           $sb=$this->getSalaireBrut($salaire_du_jour,$nb_jour);
          $salaier=array('nb_jour' => $nb_jour,'salaire_du_jour' => $salaire_du_jour);
          $pesonnel=
              Personnels::where('id', '=', $personel_id)
              ->update($salaier);
            dd($pesonnel);
         */


    }



    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $prime = Prime::findOrFail($id);

        $prime->delete();


        return redirect(route('primes.index'));
    }

    /*******************************Function Calculate***************************/

    //Calcule Salaire Brut
    public function getSalaireBrut($NJ, $SJ)
    {

        return (($NJ * $SJ) * NOMBERDUMOIS);
    }
}

resources/views/prime/create_edit.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <!--header tab -->


        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1>Listes des primes</h1>
                </div>
                <div class="col-lg-2   ">
                    <div class="pull-right ">

                        <a href="{!! URL::to('primes') !!} " class="btn btn-primary btn-primary-header  ">
                            Back
                        </a>
                    </div>
                </div>
            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- end header tab -->

        <!--container Tab -->
        <div class="row"><!-- /.row -->
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">

                    </div>
                    {!! Form::open(['url' => route('primes.store')]) !!}
                    @include('prime.form_',['submitButtonText'=>'Ajouter ']);
                    {!! Form::close() !!}
                </div><!-- /div panel- panel-default-->
            </div><!--col-lg-12 -->
        </div><!-- row -->
        <!--end container tab -->
    </div><!-- container tab -->

    </div>  <!-- /#page-wrapper -->







@endsection

resources/views/prime/form_.blade.php
<div class="panel-body">

    <div class="row">
        <!--  tab  content-->
        <div class="tab-content">
            <!-- General tab-->
            <div class="tab-pane active" id="tab-general">

                    <div class="col-lg-8 col-lg-offset-2">


                        <input type="hidden" name="_token" value="{{csrf_token()}}">

                    <div class="form-group  {{ $errors->has('description') ? 'has-error' : '' }}">
                        {!! Form::label(' Ajouter  prime') !!}
                        <div class="controls">
                            {!! Form::text('description', null, array('class' => 'form-control')) !!}
                            <span class="help-block">{{ $errors->first('description', ':message') }}</span>
                        </div>
                    </div>


                </div>  <!-- /.col-lg-6-->
            </div>     <!-- tab pane -->
        </div> <!--tab content -->

        <div class="col-lg-12">
            <div class="col-lg-3 col-lg-push-3">
                <button type="reset" class="btn btn-danger btn-block">Anuuler</button>
                </button>
            </div>
            <div class="col-lg-3  col-lg-push-3">
                            {!! Form::submit($submitButtonText,['class'=>
                            'btn btn btn-success btn-block']) !!}



            </div>
        </div>

    </div><!-- /div row -->

</div><!-- /panel-body -->

resources/views/prime/index.blade.php
@extends('layout')



@section('content')



    <div id="page-wrapper">
        <div class="row">
            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1 class="">    Listes des primes</h1>
                </div>
                <div class="col-lg-2 ">
                    <div class="pull-right ">

                        <a href="{{URL::to('primes/create')}}"
                           class="btn btn-primary btn-primary-header  ">Ajouter</a>

                    </div>
                </div>
            </div>

            </div>
            <div class="row">
                <div class="col-lg-12">
                    <div class="panel panel-default">
                        <div class="panel-heading">

                        </div>
                        <!-- /.panel-heading -->
                        <div class="panel-body">
                            <div class="dataTable_wrapper">
                                <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                    <thead>
                                    <tr>
                                        <th>Prime</th>
                                        <th></th>
                                    </tr>

                                    </thead><div class="row">
                                        @foreach ($primes as $pr)
                                            <tr>

                                                <td> {{$pr->description}} </td>
                                                <td class="col-lg-1">

                                                    @if($pr->id!=1)
                                                    {!! Form::open(array('class' => 'form-inline', 'method' => 'DELETE', 'route' => array('primes.destroy', $pr->id))) !!}



                                                    {!! Form::submit('Delete', array('class' => 'btn btn-danger')) !!}


                                                    {!! Form::close() !!}

                                                    @endif
                                                </td>

                                            </tr>


                                        @endforeach
                                    </div>

                                </table>
                            </div>
                            <!-- /.table-responsive -->

                            <!-- /.panel-body -->
                        </div>
                        <!-- /.panel -->
                    </div>
                    <!-- /.col-lg-12 -->
                </div>


                <!-- /.row -->
            </div>
        </div>


    </div>





@endsection