app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::get('personnel/delete/{task}', 'PersonnelController@getDelete');
Route::get('personnel/supprimerPersonnel/{task}', 'PersonnelController@supprimerPersonnel');

Route::get('/', 'AppController@home');
Route::get('dashborad', 'DashboradController@index');
Route::group(['namespace'=>'Admin','prefix'=>'admin'],function(){
	
 Route::resource('admins','AdminController');
});
/**************************Bulletin de Paie*********************************************************/
Route::resource('bulletinPaie','BulletinPaieController');
/**************************primes*********************************************************/
Route::resource('primes','PrimeController');


/**************************Conges*********************************************************/
Route::resource('conges','CongesController');

Route::get('conges/updateCongee/{personnel_id}', 'CongesController@updateCongee');
Route::any('conges/{conge_id}/updateCongePersonnell', 'CongesController@updateCongePersonnell');

/********************************************************************************************/
/**************************personnel*********************************************************/
Route::resource('personnel','PersonnelController');

/********************************************************************************************/
/********************Cacule salaier***********************/
Route::get('salaire', 'PersonnelController@salaire');

Route::post('calculeSalaire',['uses'=>'PersonnelController@calculeSalaire', 'as' => 'clsalaire'] );

/*********************************************************/
Route::resource('typeDeContrat','TypeDeContratController');

// Authentication routes...

//Route::get('auth/login', 'Auth\AuthController@getLogin');

Route::controllers([
	'auth' => 'Auth\AuthController',
	'password' => 'Auth\PasswordController',
]);
// Route::match(['get', 'post'], '/', 'AppController@home');
// Route::get('test', 'AppController@test');

//Route::post('auth/facebookLogin/{offline?}', 'Auth\AuthController@facebookLogin');
// Route::post('signup', 'AppController@signup');

/*Route::controllers([
    'auth' => 'Auth\AuthController',
    'password' => 'Auth\PasswordController',
]);*/

/*
|--------------------------------------------------------------------------
| Admin Routes
|--------------------------------------------------------------------------

Route::group([
    'prefix' => 'admin',
    'namespace' => 'Admin',
    'middleware' => ['auth', 'authz'],
    'roles' => ['admin'],
    'permissions' => ['can_edit']
], function()
{
    Route::get('/', ['uses' => 'AdminController@dashboard', 'as' => 'admin.dashboard']);
});
*/


/*
|--------------------------------------------------------------------------
|  Routes Journal de paie Coût Total
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieCoutTotal', 'JournalPaieCoutTotalController@index');
/*
|--------------------------------------------------------------------------
|  Routes Journal de paie IRPP
|--------------------------------------------------------------------------
*/
Route::get('JournalPaieIrpp', 'JournalPaieIrppController@index');

/*
|--------------------------------------------------------------------------
|  Routes Cnss
|--------------------------------------------------------------------------
*/
Route::get('cnss', 'CnssController@index');

/*
 ------------------------------------------------------------------------------------
Ajax
 -------------------------------------------------------------------------------------
 */

Route::get('updateAvance',['as' => 'Avance', 'uses' => 'PersonnelController@updateAvance']);

app/JournalPaieCoutTotal.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
//Nombre du Mois
define("NOMBERDUMOISJP", 12);
define("ROUNDVALUEJP", 3);
class JournalPaieCoutTotal extends Model
{
    //            $table->increments('id');

    protected $fillable = [
        'salaire_brut',
        'retenu_cnss',
        'salaier_imposable',
        'retenue_irpp',
        'salaier_net',
        'Charage_patronal',
        'tfp',
        'foprolos',
        'cout_total',
        'personnels_id',
    ];

    public function Personnels()
    {
        return $this->belongsTo('App\Personnels');
    }


    // return Retenu Cnss Mensuel
    public function getRetenuCnssAttribute($value)
    {
        return ($this->getMensuel($value));
    }
    // return salaire Brut Mensuel
    public function getSalaireBrutAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return salaire  salaier imposable
    public function getSalaierImposableAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return salaire  salaier net Mensuel
    public function getSalaierNetAttribute($value)
    {
        return ($this->getMensuel($value));
    }
    // return salaire  Charage Patronal  Mensuel
    public function getCharagePatronalAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return salaire  irrp  Mensuel
    public function getRetenueIrppAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return salaire  TFP  Mensuel
    public function getTfpAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return salaire  Foprolos  Mensuel
    public function getFoprolosAttribute($value)
    {
        return ($this->getMensuel($value));
    }

    // return Coût Toal
    public function getCouttotalAttribute($value)
    {
        return ($this->getMensuel($value));
    }
    //
    public function getMensuel($value){

        return  number_format(($value/NOMBERDUMOISJP), ROUNDVALUEJP, '.', '');;
    }
}

resources/views/jpcouttotal/index.blade.php
@extends('layout')



@section('content')

    <div id="page-wrapper">
        <div class="row">

            <div class="col-lg-12 page-header">
                <div class="col-lg-10 ">
                    <h1 class="">Table Jouranl Paie mensuel</h1>
                </div>

            </div> <!-- /.col-lg-12 -->
        </div><!-- div row -->
        <!-- /.row -->
        <div class="row">
            <div class="col-lg-12">
                <div class="panel panel-default">
                    <div class="panel-heading">
                   Jouranl Paie mensuel
                    </div>
                    <!-- /.panel-heading -->

                    <div class="panel-body">
                        <div class="dataTable_wrapper">
                            <table class="table table-striped table-bordered table-hover" id="dataTables-example">
                                <thead>
                                <tr>
                                    <th>Poste</th>
                                    <th>Nom & Prénom</th>
                                    <th>Salaire Brut</th>
                                    <th>Retenue CNSS</th>
                                    <th>Salaire Imposable</th>
                                    <th>Retenu IRPP</th>
                                    <th>Salaire Net</th>
                                    <th>Charge Patronal</th>
                                    <th>TFP</th>
                                    <th>FOPROLOS</th>
                                    <th>Coût Total</th>
                                </tr>
                                </thead><div class="row">
                                @foreach ($jpct as $ct)
                                    <tr>

                                        <td>{{$ct->post}}   </td>
                                        <td> {{$ct->prenom}} {{$ct->nom}} </td>
                                        <td>{{$ct->jpCoutTotals->salaire_brut}} </td>
                                        <td>{{$ct->jpCoutTotals->retenu_cnss}}  </td>
                                        <td>{{$ct->jpCoutTotals->salaier_imposable}}  </td>
                                        <td> {{$ct->jpCoutTotals->retenue_irpp}}  </td>
                                        <td> {{$ct->jpCoutTotals->salaier_net}}</td>
                                        <td> {{$ct->jpCoutTotals->charage_patronal}}</td>
                                        <td> {{$ct->jpCoutTotals->tfp}}</td>
                                        <td> {{$ct->jpCoutTotals->foprolos}}</td>
                                        <td>{{$ct->jpCoutTotals->cout_total}}</td>


                                    </tr>

                                @endforeach
                                </div>

                            </table>
                        </div>
                        <!-- /.table-responsive -->

                        <!-- /.panel-body -->
                    </div>
                    <!-- /.panel -->
                </div>
                <!-- /.col-lg-12 -->
            </div>


            <!-- /.row -->
        </div>
        <!-- /#page-wrapper -->




@endsection